name: Build and Release Rust Project

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
    secrets: inherit
    
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-]
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download  build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: ./builds/${{ matrix.os }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          builds/${{ matrix.os }}/arnis*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
