name: Build and Release Rust Project

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
    secrets: inherit
    
  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Windows build artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-latest-build
        path: ./builds/windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          builds/windows/arnis.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
